// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzOA4dUkTxjdshqo1na0a28p28XlMBoM',
    appId: '1:353162856816:web:3faba3347e4245a780e7b5',
    messagingSenderId: '353162856816',
    projectId: 'avantswiftsolutions',
    authDomain: 'avantswiftsolutions.firebaseapp.com',
    storageBucket: 'avantswiftsolutions.appspot.com',
    measurementId: 'G-5MF8P9FKJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7mpzuuhMKOHuod3dllnlK6rrg2NxHwzM',
    appId: '1:353162856816:android:865a97034d79dfa780e7b5',
    messagingSenderId: '353162856816',
    projectId: 'avantswiftsolutions',
    storageBucket: 'avantswiftsolutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PBYVvdwuKeuHz_tiiCwjPwYYpuzRF5c',
    appId: '1:353162856816:ios:978e956bbfccf75e80e7b5',
    messagingSenderId: '353162856816',
    projectId: 'avantswiftsolutions',
    storageBucket: 'avantswiftsolutions.appspot.com',
    iosClientId:
        '353162856816-2e0jo8mt91t5ip71navsj4tqacjbtpcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.avantswiftPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PBYVvdwuKeuHz_tiiCwjPwYYpuzRF5c',
    appId: '1:353162856816:ios:b09db27f849cd23380e7b5',
    messagingSenderId: '353162856816',
    projectId: 'avantswiftsolutions',
    storageBucket: 'avantswiftsolutions.appspot.com',
    iosClientId:
        '353162856816-u4fj0itu24mac3031g3r2s9njhi4oa2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.avantswiftPortfolio.RunnerTests',
  );
}
