name: CI/CD

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Verify formatting
      #   run: dart format .

      # - name: Analyze project source
      #   run: flutter analyze || true
      
      # - name: Install lcov
      #   run: sudo apt-get update > /dev/null && sudo apt-get install lcov > /dev/null

      # - name: Run tests with coverage
      #   run: flutter test --coverage test/controller test/models || true

      # - name: Check coverage threshold and set job status
      #   run: |
      #     coverage=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}')

      #     threshold=50.0
          
      #     if [[ "$(awk -v a=$coverage -v b=$threshold 'BEGIN { print (a >= b) }')" == "1" ]]; then
      #         echo "Code coverage is above threshold. CI/CD passes. Coverage: $coverage"
      #         exit 0
      #     else
      #         echo "Code coverage is below threshold. CI/CD fails. Coverage: $coverage"
      #         exit 1
      #     fi
      
      - name: Build web
        run: flutter build web #npm ci && npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVANTSWIFTSOLUTIONS }}'
          projectId: avantswiftsolutions
