# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Testing

on:
  push:
    branches: "feature/EP-18"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'

      - name: Install dependencies
        run: flutter pub get
    
    #   - name: Verify formatting
    #     run: dart format --output=none --set-exit-if-changed .

    #   - name: Analyze project source
    #     run: dart analyze

      - name: Run tests
        run: flutter test
