name: Testing

on:
  push:
    branches: feature/EP-18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format .

      - name: Analyze project source
        run: flutter analyze || true
      
      - name: Run tests with coverage
        run: flutter test -r compact | tee test_results.txt || true

      - name: Check coverage threshold and set job status
        run: |

          last_line=$(tail -n 1 "test_results.txt")

          passed=$(echo "$last_line" | sed -E 's/.*\+([0-9]+).*/\1/')
          failed=$(echo "$last_line" | sed -E 's/.*-([0-9]+).*/\1/')
          
          total=$((passed + failed))
          percentage=$(( (passed * 100) / total ))
          
          threshold=80
          
          if ((percentage >= threshold)); then
              echo "Code coverage is above threshold. CI/CD passes."
              exit 0
          else
              echo "Code coverage is below threshold. CI/CD fails."
              exit 1
          fi