name: Testing

on:
  push:
    branches: feature/EP-18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format .

      - name: Analyze project source
        run: flutter analyze || true
      
      - name: Run tests with coverage
        run: flutter test --coverage || true
      
      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Publish coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov.info

      - name: Check coverage threshold and set job status
        run: |
          coverage_output=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}')
          threshold=50

          if [[ -z "$coverage_output" ]]; then
            echo "Failed to calculate coverage. CI/CD fails."
            exit 1
          fi

          if (( "$coverage_output" >= "$threshold" )); then
            echo "Code coverage is above threshold. CI/CD passes."
            exit 0
          else
            echo "Code coverage is below threshold. CI/CD fails."
            exit 1
          fi