name: Testing

on:
  push:
    branches: feature/EP-18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Verify formatting
      #   run: dart format .

      # - name: Analyze project source
      #   run: flutter analyze || true
      
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install lcov

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Calculate code coverage percentage
        run: |
          coverage_percentage=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}')
          echo "Coverage Percentage: $coverage_percentage%"
        id: coverage

      - name: Publish coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report

      - name: Check coverage threshold and set job status
        run: |
          threshold=80

          if [ "$coverage_percentage" -ge "$threshold" ]; then
            echo "Code coverage is above threshold. CI/CD passes. Coverage: $coverage_percentage%"
            exit 0
          else
            echo "Code coverage is below threshold. CI/CD fails. Coverage: $coverage_percentage%"
            exit 1
          fi